target 'SwiftTKJF' do
end
platform :ios, '8.0'
use_frameworks!
pod 'ReachabilitySwift'
pod 'SnapKit', '~> 4.0.0'
pod 'Alamofire'
pod 'RxSwift'
pod 'RxCocoa'
pod 'Moya'
pod 'ObjectMapper'
pod 'Result', '~> 3.0.0'
pod 'Moya/RxSwift'
pod 'Masonry'
pod 'DGElasticPullToRefresh'
